fix: add error code number to depgraph errors [LUM-653]
snyk/container-cli pull request #21
Opened 2023-10-17 07:43 UTC by shlomiSnyk

- [ ] Tests written and linted [ℹ︎](https://github.com/snyk/general/wiki/Tests)
- [ ] Documentation written [ℹ︎](https://github.com/snyk/general/wiki/Documentation)
- [ ] Commit history is tidy [ℹ︎](https://github.com/snyk/general/wiki/Git)

### What this does

add error code number to depgraph errors 

### Notes for the reviewer

Error code nmber is the line number from where the error created.

2023-10-17 07:45 UTC, gergo-papp commented on internal/workflows/sbom/sbom.go
> +		return nil, w.errFactory.NewDepGraphWorkflowError(err, 88)
Where are these codes documented?

Could we add an enum/map so that they are not hardcoded like this? I have no idea what 88 means

2023-10-17 07:58 UTC, gergo-papp commented on internal/workflows/sbom/sbom.go
> +		return nil, w.errFactory.NewDepGraphWorkflowError(err, 88)
I think we could have an `error_codes.go` file where we consolidate all of these and link to any eternal docs

2023-10-27 10:49 UTC, gergo-papp commented on internal/workflows/sbom/sbom.go
> +		return nil, w.errFactory.NewDepGraphWorkflowError(err, 88)
that sounds impossible to maintain. are we expected to change the error code every time that file changes?

2023-10-27 10:50 UTC, gergo-papp requested changes
I really really really don't think we should make our error codes depend on the line that there are being generated from.

Let's have meaningful error names instead or log the stacktrace if we need to

2023-11-01 09:26 UTC, rmutuleanu commented
Could integrating with the Error Catalog solve our issue here?

2023-11-13 15:55 UTC, shlomiSnyk commented
@gergo-papp added error codes based on workflow and number to try to keep it unique and less prone for errors and conflict. I still feel like it's not very elegant but got dead-ends when tried to leverage the analytics. LMK this looks reasonable.

> Would integrating with the Error Catalog solve our issue here?

@rmutuleanu not initially, after talking to hammer-head there seem to be a plan to integrate the error catalog with a new error reporting flow for the CLI. the work is planned for Q1 of 2024.

2023-11-13 16:12 UTC, gergo-papp reviewed
It's nice that we are centralising how we create and log errors but I'm not sure I understand the reasoning behind this change.

- How will this make it easier for users to investigate an error?
- Will it make it any easier for us to debug? (I think it'll make it just more difficult)

2023-11-13 16:12 UTC, gergo-papp commented on internal/common/errors/error_test.go
> +	require.Equal(t, expectedErrorMessage, result)
nit: I think it would read much better if we hardcoded the expected error:

```suggestion
	require.Equal(t, "test user message [ERRA42]", result)
```

2023-11-13 16:12 UTC, gergo-papp commented on internal/common/errors/error_test.go
> +	require.Equal(t, expectedErrorMessage, result)
Otherwise I have no idea what's the expectation (`"%s [ERR#%s%d]"` is not very human-readable)

2023-11-13 16:12 UTC, gergo-papp commented on internal/common/errors/error_test.go
> +		"%s [ERR#%s%d+%s%d]", userMessage, workflowErrorCode, errorCode, nestedWorkflowErrorCode, nestedErrorCode,
same comment as above... a test's outcome should be easy to read

2023-11-13 16:18 UTC, gergo-papp commented on internal/workflows/depgraph/errors/errors.go
> +	return newDepGraphWorkflowError(
this seems odd to me: how do we know that all payload conversion errors are related to the depgraph workflow.

Are there no other HTTP calls we make that could have this error?

2023-11-13 16:59 UTC, rmutuleanu commented on internal/common/errors/error_test.go
> +	"github.com/snyk/container-cli/internal/common/errors"
Minor: goimports not run

2023-11-13 17:05 UTC, rmutuleanu commented on internal/common/errors/error.go
> +	prevErrCode := ""
Minor: since we initialize it with the zero value, we could use `var prevErrCode string` instead of using the short assignment statement.

2023-11-13 17:07 UTC, rmutuleanu commented on internal/workflows/depgraph/depgraph.go
> +	depgraphErrors "github.com/snyk/container-cli/internal/workflows/depgraph/errors"
Minor: goimports not run

2023-11-13 17:11 UTC, rmutuleanu commented on internal/workflows/depgraph/depgraph.go
> +		return nil, logErrorAndReturn(logger, extractLegacyCLIError(data, err))
Why do we need to both handle the error (log it in this case) and return it to the caller? A best practice would be to handle each error once.

I remember there was a reason for this, but I can't remember what it was.

2023-11-13 17:15 UTC, rmutuleanu commented on internal/workflows/depgraph/errors/errors.go
> +func newDepGraphWorkflowError(err error, userMsg string, errCode int) *containererrors.ContainerExtensionError {
Do we need this private function? It looks like we could use the `containererrors.NewContainerExtensionError` directly in the below functions.

2023-11-14 08:50 UTC, shlomiSnyk commented
> It's nice that we are centralising how we create and log errors but I'm not sure I understand the reasoning behind this change.

@gergo-papp currently in the CLI we are not shipping logs so we don't have a lot of visibility when things go wrong.
We have the analytics that we send with some info on failures in the flow but since the same error message is for numerous errors in the `depgraph` workflow we can't really tell what went wrong.

Since we can't change the actual user error messages we send back to the user I thought that appending an error code at the end of the message will help us differentiate exactly where the error originated.

Not the most elegant solution and the fact that we need to maintain the mapping to the error is prone for human errors as well I'm starting to think that maybe we should leave it like that for now and maybe at Q1 2024 when the new initiative for new monitoring flow for the CLI might introduced we can apply that.

2023-11-14 15:45 UTC, closed without merging